# Java config
org.gradle.java.home=/usr/lib/jvm/java-21-openjdk

# Android config
android.useAndroidX=true
android.enableJetifier=true

# Performance
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=false  # TEMPORALMENTE desactivado
org.gradle.daemon=true

# Build cache
android.enableBuildCache=false
buildCache.remote.enabled=false
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=false
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
android.builtInKotlin=false
android.newDsl=false

# Desactiva verificación problemática
# android.enableAapt2=false
